name-template: 'Release v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

template: |
  # 📦 Release v$RESOLVED_VERSION

  **Release Date:** $DATE  
  **Released By:** @ranjitm82  
  **Responsible Team:** Platform / Backend / QA *(customize as needed)*

  ## 🔖 Summary

  **Title:** $TITLE  
  **Version:** v$RESOLVED_VERSION  
  **Description:**  
  - _(Add a one-line summary manually when publishing, or auto-generate if you have descriptions in PRs)_

  ## 🚀 Included Changes

  $CHANGES

  ---

  🔗 [Compare changes](https://github.com/$OWNER/$REPOSITORY/compare/v$PREVIOUS_TAG...v$RESOLVED_VERSION)

change-template: '- $TITLE by @$AUTHOR in [#$NUMBER]($URL)'

# Optional: semantic version bumping based on labels
version-resolver:
  major:
    labels:
      - 'breaking-change'
  minor:
    labels:
      - 'feature'
  patch:
    labels:
      - 'bug'
